[tool.poetry]
name = "pyfeat-runner"
version = "0.1.0"
description = "Standalone helper to execute Py-Feat video analysis for the multimodal pipeline."
authors = ["Multimodal Pipeline Maintainers <multimodal@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
py-feat = "^0.5.0"
opencv-python = "^4.10.0"
pandas = "^2.2.0"
numpy = "^1.26.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
