[tool.poetry]
name = "nlp-models"
version = "0.1.0"
description = "Transformer and text-analytics dependency bundle for the multimodal pipeline."
authors = ["Multimodal Pipeline Maintainers <ml-pipeline@example.com>"]
packages = [
    { include = "nlp_models" }
]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = "^1.26"
torch = ">=2.6,<2.8"
transformers = "^4.39.3"
sentence-transformers = "^2.6.1"
scikit-learn = "^1.4.2"
scipy = ">=1.11,<1.13"
accelerate = "^0.29.2"
protobuf = "^4.25"
tensorflow = { version = "^2.15", optional = true }
tensorflow-hub = { version = "^0.15.0", optional = true }
tensorflow-text = { version = "^2.15.0", optional = true }
tf-keras = "^2.15"

[tool.poetry.extras]
tensorflow-stack = ["tensorflow", "tensorflow-hub", "tensorflow-text"]

[tool.poetry.group.dev.dependencies]
pytest = "^8.1"
ruff = "^0.4.4"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
